
server:
  port: 8763
  servlet:
    context-path: /auth
spring:
  application:
    name: oaut-server
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka/
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng