
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  #Mapper.xml存放位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描
  typeAliasesPackage: com.example.common.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl